package pacsus.main;
/* Generated by Together */

/**
 * For a description of Day visitors, follow hyperlink to the Administration use
 * case for issuing a new Day visitor permit.
 */
public class Day_visitor_permit extends Permit
{

    /**
     * The name of the University member hosting the visit.
     */
    private String hostName;

    /**
     * The date that the visitor is visiting on - entry will be allowed on that date
     * only.
     * 
     * @clientCardinality 1
     * @supplierCardinality 1
     * @label Visiting on
     * @link aggregation
     * @directed
     */
    private Date lnkDate;



    /**
     * constructor for creating the day permit
     * @param permitHolder name of the permit holder
     * @param permittedVehicles the reg numbers of the vehicles permitted
     * @param visiting name of the person your visiting
     * @param date date of visit
     */
    public Day_visitor_permit(String permitHolder, Vehicle_info permittedVehicles, String visiting, Date date)
    {
	super(permitHolder, permittedVehicles);
	this.hostName = visiting;
	this.lnkDate = date;
    }

    /**
     * this method returns a string representation of the permits status
     * @Override
     * @return the permits status in string form
     */
    public String getStatus()
    {
	return super.getStatus() + "\nUniversity Host member name: " + hostName + "\nDate of visit: "
		+ lnkDate.getDayNumber();
    } 
    
    /**
     * returns the lnkdate field
     */
    public Date getDate()
    {
	return lnkDate;
    }
}
