package pacsus.main;
/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the
 * Administration use case for issuing a new Permanent visitor permit.
 */
public class Permanent_visitor_permit extends Permit
{

	public Permanent_visitor_permit(String permitHolder, Vehicle_info permittedVehicles) {
		super(permitHolder, permittedVehicles);
	
	}
	
    public void checkPermanentVisitorPermitDate() {
    	
    }

    @Override
    Date getDate()
    {
	// TODO Auto-generated method stub
	return null;
    }
}
