package pacsus.main;

import java.util.Hashtable;

/* Generated by Together */

/**
 * Vehicle list manages the collection of vehicles currently associated with
 * permits. It handles checks of whether vehicles are allowed through the
 * barriers, records warnings, and various other functions. Note that each
 * Vehicle_info object must have a unique registration number, to allow sensible
 * checking and recording of entries onto the campus (so a HashTable is probably
 * a good implementation of the collection, with registration number as key).
 *
 * There will only be one instance of this class.
 */
public class Vehicle_list
{
    /**
     * The Vehicle list maintains a collection of the known Vehicle_infos associated
     * with all permits. This association must be implemented by an attribute
     * holding a collection data structure (for example: array, hash table - the
     * latter is recommended).
     *
     * Note that no two Vehicle_infos may have the same registration number (this
     * information is not represented diagrammatically) - this is to guarantee
     * consistency with the constraint that no vehicle is associated with more than
     * one permit.
     *
     * Note that, given a registration number, the Vehicle_list can look up the
     * appropriate Vehicle_info instance, and via that it can obtain the vehicle's
     * permit information.
     * 
     * @associates Vehicle_info
     * @label Contains
     * @clientCardinality 1
     * @supplierCardinality 0..*
     * @directed
     */
    private java.util.Hashtable<Vehicle_info, String> lnkVehicle;

    public Vehicle_list()
    {
	lnkVehicle = new Hashtable<Vehicle_info, String>();
    }

    public boolean add(Vehicle_info key, String info)
    {
	if (!lnkVehicle.containsValue(info))
	{
	    lnkVehicle.put(key, info);
	    System.out.println("Added: " + key + " " + info);
	    return true;

	}
	else
	{
	    System.out.println("Not added");
	    return false;
	}

    }

    public Hashtable<Vehicle_info, String> updateList()
    {
	return this.lnkVehicle;
    }

//    public boolean containsKey(Vehicle_info key)
//    {
//	if (lnkVehicle.containsKey(key))
//	{
//	    System.out.println("Key: " + key + " was contained");
//	    return true;
//	}
//	else
//	{
//	    System.out.println("fuck you");
//	    return false;
//	}
//    }

    public boolean findVehicle(String regNo)
    {
	Object[] vh = lnkVehicle.keySet().toArray();

	for (Object object : vh)
	{
	    if (object.toString().equals(regNo))
	    {
		return true;
	    }
	}
	return false;
    }

    @Override
    public String toString()
    {
	return "Vehicle_list [lnkVehicle=" + lnkVehicle + "]";
    }

}
