package pacsus.main.permits;
/* Generated by Together */

import pacsus.main.utility.Date;
import pacsus.main.vehicles.Vehicle_info;

/**
 * For a description of Permanent visitors, follow hyperlink to the
 * Administration use case for issuing a new Permanent visitor permit.
 */
public class Permanent_visitor_permit extends Permit
{
    /**
     * the constructor for creaating permanant visitor permits
     * 
     * @param permitHolder      name of permit holder
     * @param permittedVehicles reg numbers of the permit holders vehicles
     */
    public Permanent_visitor_permit(String permitHolder, Vehicle_info permittedVehicles)
    {
	super(permitHolder, permittedVehicles);

    }

    /**
     * this method is here to avoid errors since there is no date for permanent
     * visitors since their permit is permanent
     */
    public void checkPermanentVisitorPermitDate()
    {

    }

    /**
     * doesn't return anything since permanent permit
     * 
     * @Override
     */
    public Date getDate()
    {
	return null;
    }
}
